### ISSUE TITLE
Ability to pin sub-dependencies at a lower version?

### ISSUE THREAD

**Issue by timmahon** [ikvm-revived/ikvm-maven#26]
I'm trying to use the following Maven Reference in a project with IKVM.Maven.Sdk version 1.1.1:-

````
<MavenReference Include="org.eclipse.jdt:org.eclipse.jdt.core:3.26.0"/>
````

While this correctly produces the dll for the main jar, the dependencies (org.eclipse.core.runtime etc) of this jar do not convert to .NET correctly as it appears they are compiled with a later version of java, so the resultant dlls do not have .net code in side of them.

I have attempted to "pin" a sub-dependency at a version that are compatible with java 8 by including a lower version as another maven reference:-

```
<MavenReference Include="org.eclipse.jdt:org.eclipse.jdt.core:3.26.0"/>
<MavenReference Include="org.eclipse.platform:org.eclipse.core.runtime:3.22.0"/>
```

however this results with a error

```
Error NullReferenceException: Object reference not set to an instance of an object.
   at IKVM.Maven.Sdk.Tasks.Aether.VersionConstraintJsonConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer) in D:\Work\ikvm-maven\src\IKVM.Maven.Sdk.Tasks\Aether\VersionConstraintJsonConverter.cs:line 52
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   
... rest snipped for brevity
````

Is there any other way or a workaround for telling ikvm-maven to use a lower version of a sub-dependency?

**Comment by wasabii** [comment]
Well, we do exactly what Maven does. So if there's a way to do this in Maven, it should be working for us as well.

**Comment by wasabii** [comment]
The error received here should be resolved in 1.4. Due to a problem dealing with version ranged constraints.
