### ISSUE TITLE
Attempting to use IKVM in tests for .NET 6.0 and other unsupported targets

### ISSUE THREAD

**Issue by NightOwl888** [ikvm-revived/ikvm-maven#28]
To work around the limitation of IKVM only compiling on .NET Core 3.1 I set up the project as follows.

## ICU4N.IKVM 

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net461;netcoreapp3.1</TargetFrameworks>
    <!-- This project is only for testing purposes-->
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="IKVM.Maven.Sdk" Version="1.2.0" />
  </ItemGroup>

  <ItemGroup>
    <MavenReference Include="com.ibm.icu:icu4j" Version="60.1" />
  </ItemGroup>

</Project>
```

## IKVM.Tests

Since we have no need for an actual ICU4N.IKVM.dll file, this project depends only on the DLLs that are generated by the ICU4N.IKVM project.

```xml
<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <RootNamespace>ICU4N</RootNamespace>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>$(NoWarn);1701;1702</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(TargetFramework)' != 'net452' ">
    <DefineConstants>$(DefineConstants);FEATURE_IKVM</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\TestAssemblyInfo.cs" Link="Properties\TestAssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Dev\Data\IDNATestInput.txt" />
    <EmbeddedResource Include="Dev\Data\TestData\*" />
    <EmbeddedResource Include="Dev\Data\TestData\unicode\*" />
    <EmbeddedResource Include="Dev\Test\Rbbi\rbbitst.txt" />
    <EmbeddedResource Include="Dev\Test\Util\Trie2Test.setRanges1.16.tri2" />
    <EmbeddedResource Include="Dev\Test\Util\Trie2Test.setRanges1.32.tri2" />
    <EmbeddedResource Include="Dev\Test\Util\Trie2Test.setRanges2.16.tri2" />
    <EmbeddedResource Include="Dev\Test\Util\Trie2Test.setRanges2.32.tri2" />
    <EmbeddedResource Include="Dev\Test\Util\Trie2Test.setRanges3.16.tri2" />
    <EmbeddedResource Include="Dev\Test\Util\Trie2Test.setRanges3.32.tri2" />
    <EmbeddedResource Include="Dev\Test\Util\Trie2Test.setRangesEmpty.16.tri2" />
    <EmbeddedResource Include="Dev\Test\Util\Trie2Test.setRangesEmpty.32.tri2" />
    <EmbeddedResource Include="Dev\Test\Util\Trie2Test.setRangesSingleValue.16.tri2" />
    <EmbeddedResource Include="Dev\Test\Util\Trie2Test.setRangesSingleValue.32.tri2" />
    <EmbeddedResource Include="Dev\Test\Rbbi\break_rules\*" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\src\ICU4N\ICU4N.csproj" />
  </ItemGroup>
  
  <ItemGroup Condition=" '$(TargetFramework)' != 'net452' ">
    <ProjectReference Include="..\..\src\ICU4N.IKVM\ICU4N.IKVM.csproj" />
  </ItemGroup>
  
  <ItemGroup Condition=" !$(TargetFramework.StartsWith('net4')) ">
    <Reference Include="icu4j">
      <HintPath>..\..\src\ICU4N.IKVM\bin\$(Configuration)\netcoreapp3.1\icu4j.dll</HintPath>
    </Reference>
  </ItemGroup>
  
  <ItemGroup Condition=" $(TargetFramework.StartsWith('net4')) And '$(TargetFramework)' != 'net452' ">
    <Reference Include="icu4j">
      <HintPath>..\..\src\ICU4N.IKVM\bin\$(Configuration)\net461\icu4j.dll</HintPath>
    </Reference>
  </ItemGroup>
  
  <ItemGroup>
    <None Update="Support\Text\UnicodeSetPartialTestExtension.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>UnicodeSetPartialTestExtension.cs</LastGenOutput>
    </None>
  </ItemGroup>
  
  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>
  
  <ItemGroup>
    <Compile Update="Support\Text\UnicodeSetPartialTestExtension.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>UnicodeSetPartialTestExtension.tt</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
```

Locallly this works fine. However, on Azure DevOps when I build this using the .NET SDK 6.0.405, I get the following error:

```
2023-01-17T03:01:16.5764742Z ##[error]C:\Users\VssAdministrator\.nuget\packages\ikvm\8.4.0\buildTransitive\netstandard2.0\IKVM.Tasks.targets(31,9): Error MSB4018: The "IkvmCompiler" task failed unexpectedly.
System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\a\1\s\tests\ICU4N.Tests.Transliterator\obj\Release\netcoreapp3.1\ikvm\stage\1\6267515b4c737594b181e1337fb0b1a5\icu4j.dll.rsp'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.WriteAllText(String path, String contents)
   at IKVM.Tools.Runner.Compiler.IkvmCompilerLauncher.ExecuteAsync(IkvmCompilerOptions options, Cancellation*** cancellation***) in D:\a\ikvm\ikvm\src\IKVM.Tools.Runner\Compiler\IkvmCompilerLauncher.cs:line 259
   at IKVM.MSBuild.Tasks.IkvmCompiler.ExecuteAsync(IkvmToolTaskDiagnosticWriter writer, Cancellation*** cancellation***) in D:\a\ikvm\ikvm\src\IKVM.MSBuild.Tasks\IkvmCompiler.cs:line 273
   at IKVM.MSBuild.Tasks.IkvmToolExecTask.Execute() in D:\a\ikvm\ikvm\src\IKVM.MSBuild.Tasks\IkvmToolExecTask.cs:line 79
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
2023-01-17T03:01:16.5781982Z      2023-01-17T03:01:16.5781982Z      7>C:\Users\VssAdministrator\.nuget\packages\ikvm\8.4.0\buildTransitive\netstandard2.0\IKVM.Tasks.targets(31,9): error MSB4018: The "IkvmCompiler" task failed unexpectedly. [D:\a\1\s\src\ICU4N.IKVM\ICU4N.IKVM.csproj]
2023-01-17T03:01:16.5784780Z C:\Users\VssAdministrator\.nuget\packages\ikvm\8.4.0\buildTransitive\netstandard2.0\IKVM.Tasks.targets(31,9): error MSB4018: System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\a\1\s\tests\ICU4N.Tests.Transliterator\obj\Release\netcoreapp3.1\ikvm\stage\1\6267515b4c737594b181e1337fb0b1a5\icu4j.dll.rsp'. [D:\a\1\s\src\ICU4N.IKVM\ICU4N.IKVM.csproj]
2023-01-17T03:01:16.5787763Z C:\Users\VssAdministrator\.nuget\packages\ikvm\8.4.0\buildTransitive\netstandard2.0\IKVM.Tasks.targets(31,9): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options) [D:\a\1\s\src\ICU4N.IKVM\ICU4N.IKVM.csproj]
2023-01-17T03:01:16.5790375Z C:\Users\VssAdministrator\.nuget\packages\ikvm\8.4.0\buildTransitive\netstandard2.0\IKVM.Tasks.targets(31,9): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) [D:\a\1\s\src\ICU4N.IKVM\ICU4N.IKVM.csproj]
2023-01-17T03:01:16.5793461Z C:\Users\VssAdministrator\.nuget\packages\ikvm\8.4.0\buildTransitive\netstandard2.0\IKVM.Tasks.targets(31,9): error MSB4018:    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) [D:\a\1\s\src\ICU4N.IKVM\ICU4N.IKVM.csproj]
2023-01-17T03:01:16.5796274Z C:\Users\VssAdministrator\.nuget\packages\ikvm\8.4.0\buildTransitive\netstandard2.0\IKVM.Tasks.targets(31,9): error MSB4018:    at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize) [D:\a\1\s\src\ICU4N.IKVM\ICU4N.IKVM.csproj]
2023-01-17T03:01:16.5798884Z C:\Users\VssAdministrator\.nuget\packages\ikvm\8.4.0\buildTransitive\netstandard2.0\IKVM.Tasks.targets(31,9): error MSB4018:    at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize) [D:\a\1\s\src\ICU4N.IKVM\ICU4N.IKVM.csproj]
2023-01-17T03:01:16.5801482Z C:\Users\VssAdministrator\.nuget\packages\ikvm\8.4.0\buildTransitive\netstandard2.0\IKVM.Tasks.targets(31,9): error MSB4018:    at System.IO.File.WriteAllText(String path, String contents) [D:\a\1\s\src\ICU4N.IKVM\ICU4N.IKVM.csproj]
2023-01-17T03:01:16.5804948Z C:\Users\VssAdministrator\.nuget\packages\ikvm\8.4.0\buildTransitive\netstandard2.0\IKVM.Tasks.targets(31,9): error MSB4018:    at IKVM.Tools.Runner.Compiler.IkvmCompilerLauncher.ExecuteAsync(IkvmCompilerOptions options, Cancellation*** cancellation***) in D:\a\ikvm\ikvm\src\IKVM.Tools.Runner\Compiler\IkvmCompilerLauncher.cs:line 259 [D:\a\1\s\src\ICU4N.IKVM\ICU4N.IKVM.csproj]
2023-01-17T03:01:16.5811063Z C:\Users\VssAdministrator\.nuget\packages\ikvm\8.4.0\buildTransitive\netstandard2.0\IKVM.Tasks.targets(31,9): error MSB4018:    at IKVM.MSBuild.Tasks.IkvmCompiler.ExecuteAsync(IkvmToolTaskDiagnosticWriter writer, Cancellation*** cancellation***) in D:\a\ikvm\ikvm\src\IKVM.MSBuild.Tasks\IkvmCompiler.cs:line 273 [D:\a\1\s\src\ICU4N.IKVM\ICU4N.IKVM.csproj]
2023-01-17T03:01:16.5814477Z C:\Users\VssAdministrator\.nuget\packages\ikvm\8.4.0\buildTransitive\netstandard2.0\IKVM.Tasks.targets(31,9): error MSB4018:    at IKVM.MSBuild.Tasks.IkvmToolExecTask.Execute() in D:\a\ikvm\ikvm\src\IKVM.MSBuild.Tasks\IkvmToolExecTask.cs:line 79 [D:\a\1\s\src\ICU4N.IKVM\ICU4N.IKVM.csproj]
2023-01-17T03:01:16.5817310Z C:\Users\VssAdministrator\.nuget\packages\ikvm\8.4.0\buildTransitive\netstandard2.0\IKVM.Tasks.targets(31,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [D:\a\1\s\src\ICU4N.IKVM\ICU4N.IKVM.csproj]
2023-01-17T03:01:16.5820431Z C:\Users\VssAdministrator\.nuget\packages\ikvm\8.4.0\buildTransitive\netstandard2.0\IKVM.Tasks.targets(31,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [D:\a\1\s\src\ICU4N.IKVM\ICU4N.IKVM.csproj]
```

[Complete build log](https://dev.azure.com/ICU4N/44041e22-bd88-42a2-ad29-ee6859a5010e/_apis/build/builds/183/logs/18)

Being that ICU4N.Tests.Transliterator has no dependencies on  ICU4N.Tests, ICU4N.IKVM or IKVM at all, I am puzzled why IKVM would even be firing at all in this project.

Given that I made a non-standard setup to get IKVM.Maven.Sdk to build my DLLs and then referenced them in projects built on later versions of .NET Core, I suspect that IKVM is getting confused because of that, but it could be another reason.

You can view my project setup where this occurred in [this commit](https://github.com/NightOwl888/ICU4N/tree/795a2940646e7f09ca4d85494298dae3cb721d64).

Thoughts on what is happening? Is there any straightforward way to prevent IKVM from trying to locate `D:\a\1\s\tests\ICU4N.Tests.Transliterator\obj\Release\netcoreapp3.1\ikvm\stage\1\6267515b4c737594b181e1337fb0b1a5\icu4j.dll.rsp`?

**Comment by wasabii** [comment]
I'm not sure what's going on here. What is this limitation you're speaking of? IKVM reference works fine on > 3.1

**Comment by NightOwl888** [comment]
I thought it couldn't be in a project that targets anything but netcoreapp3.1...?

**Comment by wasabii** [comment]
Nope. That has never been a thing.

**Comment by NightOwl888** [comment]
Okay. I will try adding the dependency to IKVM.Maven.Sdk directly in the test project, then.

**Comment by NightOwl888** [comment]
At least it is looking for an rsp file for the right project this time, but it still cannot find it for .NET 5.0.

```
2023-01-17T04:04:38.0072354Z ##[error]C:\Users\VssAdministrator\.nuget\packages\ikvm\8.4.0\buildTransitive\netstandard2.0\IKVM.Tasks.targets(31,9): Error MSB4018: The "IkvmCompiler" task failed unexpectedly.
System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\a\1\s\src\ICU4N.TestFramework\obj\Release\net5.0\ikvm\stage\1\6267515b4c737594b181e1337fb0b1a5\icu4j.dll.rsp'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.WriteAllText(String path, String contents)
   at IKVM.Tools.Runner.Compiler.IkvmCompilerLauncher.ExecuteAsync(IkvmCompilerOptions options, Cancellation*** cancellation***) in D:\a\ikvm\ikvm\src\IKVM.Tools.Runner\Compiler\IkvmCompilerLauncher.cs:line 259
   at IKVM.MSBuild.Tasks.IkvmCompiler.ExecuteAsync(IkvmToolTaskDiagnosticWriter writer, Cancellation*** cancellation***) in D:\a\ikvm\ikvm\src\IKVM.MSBuild.Tasks\IkvmCompiler.cs:line 273
   at IKVM.MSBuild.Tasks.IkvmToolExecTask.Execute() in D:\a\ikvm\ikvm\src\IKVM.MSBuild.Tasks\IkvmToolExecTask.cs:line 79
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```

**Comment by NightOwl888** [comment]
The tests run fine locally.

However the file `ICU4N.TestFramework\obj\Release\net5.0\ikvm\stage\1\6267515b4c737594b181e1337fb0b1a5\icu4j.dll.rsp` doesn't exist locally, either.

Our build runs `dotnet publish` on the test projects to ensure all of the dependencies are included in the test binary artifacts. It appears to be failing during the publish stage.

**Comment by NightOwl888** [comment]
Superseded by #29
